### ISSUE TITLE
ShadowShard Whois bug

### ISSUE THREAD

**Issue by Rishik01** [mattsilver1/ShadowShard#9]
**Discord Information**
Discord Username with Discriminator:Rishik01#7125
If you can provide, what is your user ID: N/A
What is your role in the Fortnite Community server: Regular

**Describe the bug**
It's saying that the account creation date on the whois command is undefined, which isn’t supposed to be happening

**To Reproduce**
Steps to reproduce the behavior: Use the whois command
#

**Expected behavior**
It should show the account creation date, which it isn’t.

**Screenshots**

**Additional context**

**Comment by mattsilver1** [comment]
Issue is already opened, please refer to #6 for more information.
